
var apertura=[
	{
		nombre: "Siciliana Dragón",
		posicionInicial: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
		variante: [
			{
				id: 0,
				nombre: "celada1",
				jugadasCPU: ['e4','Nf3','d4','Nxd4','Nc3','f4','Nf3','END'],
				jugadasPlayer: ['c5','d6','cxd4','Nf6','g6','Nbd7','Qc7'],
				jugadaError: ['-','-','-','-','-','Bg7','Bg7'],
				explicacionError: 'Ojo que te quedas sin caballo o sin dama si mueves el rey en vez del alfil!',
				simulacionErrorCPU: ['e5','fxe5','Bb5+','Qxg4'],
				simulacionErrorPlayer: ['dxe5','Ng4','Bd7','END']
			},

			{
				id: 1,
				nombre: "principal-1",
				jugadasCPU: ['e4','Nf3','d4','Nxd4','Nc3','Be3','f3','Qd2','O-O-O','Bxd4','g4','a3','h4','END'],
				jugadasPlayer: ['c5','d6','cxd4','Nf6','g6','Bg7','O-O','Nc6','Nxd4','Be6','Qa5','Rfc8','Rab8'],
				jugadaError: ['-','-','-','-','-','-','-'],
				explicacionError: '',
				simulacionErrorCPU: [],
				simulacionErrorPlayer: []
			},
			{
				id: 2,
				nombre: "principal-2",
				jugadasCPU: ['e4','Nf3','d4','Nxd4','Nc3','Be3','f3','Qd2','O-O-O','Bxd4','g4','Kb1','a3','END'],
				jugadasPlayer: ['c5','d6','cxd4','Nf6','g6','Bg7','O-O','Nc6','Nxd4','Be6','Qa5','Rfc8','Rab8'],
				jugadaError: ['-','-','-','-','-','-','-'],
				explicacionError: '',
				simulacionErrorCPU: [],
				simulacionErrorPlayer: []
			},
			{
				id: 3,
				nombre: "principal-3",
				jugadasCPU: ['e4','Nf3','d4','Nxd4','Nc3','Be3','f3','Qd2','O-O-O','Bxd4','Kb1','g4','h4','a3','END'],
				jugadasPlayer: ['c5','d6','cxd4','Nf6','g6','Bg7','O-O','Nc6','Nxd4','Be6','Qc7','Rfc8','Qa5','Rab8'],
				jugadaError: ['-','-','-','-','-','-','-','-','-','-','Qa5','-','-'],
				explicacionError: 'Que te come el caballito',
				simulacionErrorCPU: ['Nd5','Nxe7+','Rxd2'],
				simulacionErrorPlayer: ['Qxd2','Kh8','END']
			},
			{
				id: 4,
				nombre: "principal-4",
				jugadasCPU: ['e4','Nf3','d4','Nxd4','Nc3','Be3','f3','Qd2','O-O-O','Bxd4','Kb1','g4','h4','h5','Bxc3','Kc1','END'],
				jugadasPlayer: ['c5','d6','cxd4','Nf6','g6','Bg7','O-O','Nc6','Nxd4','Be6','Qc7','Rfc8','Qa5','Rxc3','Qxa2+','Qa1#'],
				jugadaError: ['-','-','-','-','-','-','-','-','-','-','-','-','-'],
				explicacionError: '',
				simulacionErrorCPU: [],
				simulacionErrorPlayer: []
			},
			{
				id: 5,
				nombre: "principal-5",
				jugadasCPU: ['e4','Nf3','d4','Nxd4','Nc3','Be3','f3','Qd2','O-O-O','Bxd4','Kb1','g4','h4','h5','Qxc3','Kc1','Be3','Qd2','END'],
				jugadasPlayer: ['c5','d6','cxd4','Nf6','g6','Bg7','O-O','Nc6','Nxd4','Be6','Qc7','Rfc8','Qa5','Rxc3','Qxa2+','Bh6+','Rc8','Qa1#'],
				jugadaError: ['-','-','-','-','-','-','-','-','-','-','-','-','-'],
				explicacionError: '',
				simulacionErrorCPU: [],
				simulacionErrorPlayer: []
			},
			{
				id: 6,
				nombre: "principal-6",
				jugadasCPU: ['e4','Nf3','d4','Nxd4','Nc3','Be3','f3','Qd2','O-O-O','Bxd4','Kb1','g4','h4','h5','Qxc3','Kc1','Be3','Qd3','Qxe3','Kd2','END'],
				jugadasPlayer: ['c5','d6','cxd4','Nf6','g6','Bg7','O-O','Nc6','Nxd4','Be6','Qc7','Rfc8','Qa5','Rxc3','Qxa2+','Bh6+','Rc8','Bxe3+','Qa1+','Qxb2'],
				jugadaError: ['-','-','-','-','-','-','-','-','-','-','-','-','-'],
				explicacionError: '',
				simulacionErrorCPU: [],
				simulacionErrorPlayer: []
			},
			{
				id: 7,
				nombre: "principal-7",
				jugadasCPU: ['e4','Nf3','d4','Nxd4','Nc3','Be3','f3','Qd2','Bc4','O-O-O','Bb3','END'],
				jugadasPlayer: ['c5','d6','cxd4','Nf6','g6','Bg7','O-O','Nc6','Bd7','Rc8','Ne5'],
				jugadaError: ['-','-','-','-','-','-','-','-','-','-','-','-','-'],
				jugadasAlternativas: ['-','-','-','-','-','-','-','-','Nd7'],
				variante: ['-','-','-','-','-','-','-','-','8'],
				explicacionError: '',
				simulacionErrorCPU: [],
				simulacionErrorPlayer: []
			},
			{
				id: 8,
				nombre: "principal-8",
				jugadasCPU: ['e4','Nf3','d4','Nxd4','Nc3','Be3','f3','Qd2','Bc4','O-O-O','Bb3','Qe2','END'],
				jugadasPlayer: ['c5','d6','cxd4','Nf6','g6','Bg7','O-O','Nc6','Nd7','Nb6','Na5','Bd7'],
				jugadaError: ['-','-','-','-','-','-','-','-','-','-','-','-','-'],
				jugadasAlternativas: ['-','-','-','-','-','-','-','-','Bd7'],
				variante: ['-','-','-','-','-','-','-','-','7'],
				explicacionError: '',
				simulacionErrorCPU: [],
				simulacionErrorPlayer: []
			},
			{
				id: 9,
				nombre: "Aleksic, Nenad (2425) contra Tiviakov, Sergei (2535)",
				jugadasCPU: ['e4','Nf3','d4','Nxd4','Nc3','Be3','Bc4','O-O','h3','Bb3','Re1','Qe2','bxc3','Bd2','Qxd2','END'],
				jugadasPlayer: ['c5','d6','cxd4','Nf6','g6','Bg7','O-O','Nc6','Bd7','Rc8','Ne5','Rxc3','Nxe4','Nxd2','e6'],
				jugadaError: ['-','-','-','-','-','-','-'],
				explicacionError: '',
				simulacionErrorCPU: [],
				simulacionErrorPlayer: []
			},
		],
		
			
			
		orientation: 'black'
	},
	{
		nombre: "Caro Khan",
		posicionInicial: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
		variante: [
			{
				id: 0,
				nombre: "principal-1",
				jugadasCPU: ['e4','Nc3','Nf3','h3','Qxf3','d4','Bd3','Nxe4','c3','O-O','END'],
				jugadasPlayer: ['c6','d5','Bg4','Bxf3','e6','Nf6','dxe4','Qxd4','Qd8','Nbd7'],
				jugadaError: ['-','-','-','-','-','-','-'],
				explicacionError: '',
				simulacionErrorCPU: [],
				simulacionErrorPlayer: [],
				jugadasAlternativas: ['-','-','-','-','-','-','-','-','-','Nxe4'],
				variante: ['-','-','-','-','-','-','-','-','-','2'],
			},
			{
				id: 1,
				nombre: "variante1",
				jugadasCPU: ['e4','Nc3','Nf3','h3','Qxf3','d4','e5','END'],
				jugadasPlayer: ['c6','d5','Bg4','Bxf3','e6','Nf6','Nfd7'],
				jugadaError: ['-','-','-','-','-','-','-'],
				explicacionError: '',
				simulacionErrorCPU: [],
				simulacionErrorPlayer: [],
				jugadasAlternativas: [],
				variante: [],
			},
			{
				id: 2,
				nombre: "principal-1",
				jugadasCPU: ['e4','Nc3','Nf3','h3','Qxf3','d4','Bd3','Nxe4','c3','O-O','Bxe4','END'],
				jugadasPlayer: ['c6','d5','Bg4','Bxf3','e6','Nf6','dxe4','Qxd4','Qd8','Nxe4','Bd6'],
				jugadaError: ['-','-','-','-','-','-','-'],
				explicacionError: '',
				simulacionErrorCPU: [],
				simulacionErrorPlayer: [],
				jugadasAlternativas: ['-','-','-','-','-','-','-','-','-','Nbd7'],
				variante: ['-','-','-','-','-','-','-','-','-','0'],
			},
			{
				id: 3,
				nombre: "principal-1",
				jugadasCPU: ['e4','c4','exd5','cxd5','Qa4+','Nc3','Nf3','Bc4','d3','Qa3','O-O','END'],
				jugadasPlayer: ['c6','d5','cxd5','Nf6','Nbd7','g6','Bg7','a6','O-O','b6','Bb7'],
				jugadaError: ['-','-','-','-','-','-','-'],
				explicacionError: '',
				simulacionErrorCPU: [],
				simulacionErrorPlayer: [],
				jugadasAlternativas: ['-','-','-','-','-','-','-','-','-','-'],
				variante: ['-','-','-','-','-','-','-','-','-','-'],
			},
			{
				id: 4,
				nombre: "variante del cambio",
				jugadasCPU: ['e4','d4','exd5','Bd3','c3','Nf3','END'],
				jugadasPlayer: ['c6','d5','cxd5','Nc6','Qc7','Bg4'],
				jugadaError: ['-','-','-','-','-','-','-'],
				explicacionError: '',
				simulacionErrorCPU: [],
				simulacionErrorPlayer: [],
				jugadasAlternativas: ['-','-','-','Nf6'],
				variante: ['-','-','-','5'],
			},
			{
				id: 5,
				nombre: "variante del cambio",
				jugadasCPU: ['e4','d4','exd5','Bd3','END'],
				jugadasPlayer: ['c6','d5','cxd5','Nf6'],
				jugadaError: ['-','-','-','-','-','-','-'],
				explicacionError: '',
				simulacionErrorCPU: [],
				simulacionErrorPlayer: [],
				jugadasAlternativas: ['-','-','-','Nc6'],
				variante: ['-','-','-','-','-','-','4'],
			},
			{
				id: 6,
				nombre: "variante del cambio - Ataque Panov",
				jugadasCPU: ['e4','d4','exd5','c4','Nc3','Nf3','cxd5','Qb3','gxf3','Qxb7','Bb5+','Qc6+','Qxb5','Nxd5','Qxd5','Be3','O-O-O','Kb1','Re1','END'],
				jugadasPlayer: ['c6','d5','cxd5','Nf6','Nc6','Bg4','Nxd5','Bxf3','e6','Nxd4','Nxb5','Ke7','Qd7','Qxd5','exd5','Ke6','Rc8+','Bc5','Kd6'],
				jugadaError: ['-','-','-','-','-','-','-'],
				explicacionError: '',
				simulacionErrorCPU: [],
				simulacionErrorPlayer: [],
				jugadasAlternativas: ['-','-','-','-','-','-','-','-','-','-'],
				variante: ['-','-','-','-','-','-','-','-','-','-'],
			},
			{
				id: 7,
				nombre: "variante del cambio",
				jugadasCPU: ['e4','d4','exd5','Bd3','c3','h3','Ne2','dxe5','Bc2','Bg5','Be3','Qxd5','Qd4','END'],
				jugadasPlayer: ['c6','d5','cxd5','Nc6','Qc7','Nf6','e5','Nxe5','Bd6','Ne4','O-O','Nf6','b6'],
				jugadaError: ['-','-','-','-','-','-','-'],
				explicacionError: '',
				simulacionErrorCPU: [],
				simulacionErrorPlayer: [],
				jugadasAlternativas: ['-','-','-','Nf6'],
				variante: ['-','-','-','5'],
			},
			{
				id: 8,
				nombre: "variante del cambio",
				jugadasCPU: ['e4','d4','exd5','Bd3','c3','Ne2','Bf4','Nxf4','Kxd1','END'],
				jugadasPlayer: ['c6','d5','cxd5','Nc6','Qc7','Bg4','Qxf4','Bxd1','e6'],
				jugadaError: ['-','-','-','-','-','-','-'],
				explicacionError: '',
				simulacionErrorCPU: [],
				simulacionErrorPlayer: [],
				jugadasAlternativas: ['-','-','-','Nf6'],
				variante: ['-','-','-','5'],
			},
			{
				id: 9,
				nombre: "variante del cambio",
				jugadasCPU: ['e4','d4','exd5','Bd3','c3','Ne2','f3','Bf4','dxe5','O-O','Na3','Nc2','Ncd4','END'],
				jugadasPlayer: ['c6','d5','cxd5','Nc6','Qc7','Bg4','Bd7','e5','Nxe5','Bd6','a6','Nf6','Nh5'],
				jugadaError: ['-','-','-','-','-','-','-'],
				explicacionError: '',
				simulacionErrorCPU: [],
				simulacionErrorPlayer: [],
				jugadasAlternativas: ['-','-','-','Nf6'],
				variante: ['-','-','-','5'],
			},
			{
				id: 10,
				nombre: "variante del cambio - Ataque Panov",
				jugadasCPU: ['e4','d4','exd5','c4','Nc3','Nf3','Bg5','Bxf6','cxd5','dxc6','bxc3','Ke2','END'],
				jugadasPlayer: ['c6','d5','cxd5','Nf6','Nc6','Bg4','Qa5','exf6','Bb4','Bxc3+','Qxc3+','O-O'],
				jugadaError: ['-','-','-','-','-','-','-'],
				explicacionError: '',
				simulacionErrorCPU: [],
				simulacionErrorPlayer: [],
				jugadasAlternativas: ['-','-','-','-','-','-','-','-','-','-'],
				variante: ['-','-','-','-','-','-','-','-','-','-'],
			},
			{
				id: 11,
				nombre: "variante del cambio - Ataque Panov",
				jugadasCPU: ['e4','d4','exd5','c4','Nc3','Nf3','cxd5','Bc4','O-O','Nxd5','END'],
				jugadasPlayer: ['c6','d5','cxd5','Nf6','Nc6','Bg4','Nxd5','e6','Be7','exd5'],
				jugadaError: ['-','-','-','-','-','-','-'],
				explicacionError: '',
				simulacionErrorCPU: [],
				simulacionErrorPlayer: [],
				jugadasAlternativas: ['-','-','-','-','-','-','-','-','-','-'],
				variante: ['-','-','-','-','-','-','-','-','-','-'],
			},
			{
				id: 12,
				nombre: "variante del cambio - Ataque Panov",
				jugadasCPU: ['e4','d4','exd5','c4','Nc3','Nf3','cxd5','Qb3','gxf3','Qxb7','Bb5+','Qc6+','Qc5+','Nxd5','O-O','Qxd5','Qe5+','Rd1','Qf5+','Qf7+','END'],
				jugadasPlayer: ['c6','d5','cxd5','Nf6','Nc6','Bg4','Nxd5','Bxf3','e6','Nxd4','Nxb5','Ke7','Nd6','cxd5','Qc8','Qb7','Kd7','Re8','Re6','Be7'],
				jugadaError: ['-','-','-','-','-','-','-'],
				explicacionError: '',
				simulacionErrorCPU: [],
				simulacionErrorPlayer: [],
				jugadasAlternativas: ['-','-','-','-','-','-','-','-','-','-'],
				variante: ['-','-','-','-','-','-','-','-','-','-'],
			},
			{
				id: 13,
				nombre: "variante del cambio - Ataque Panov",
				jugadasCPU: ['e4','d4','exd5','c4','Nc3','Nf3','cxd5','Qb3','gxf3','Qxb7','Bb5+','Qc6+','Qxb5','Qa5','Qxc3','Be3','O-O','END'],
				jugadasPlayer: ['c6','d5','cxd5','Nf6','Nc6','Bg4','Nxd5','Bxf3','e6','Nxd4','Nxb5','Ke7','Qd7','Nxc3','f6','Kf7','Be7'],
				jugadaError: ['-','-','-','-','-','-','-'],
				explicacionError: '',
				simulacionErrorCPU: [],
				simulacionErrorPlayer: [],
				jugadasAlternativas: ['-','-','-','-','-','-','-','-','-','-'],
				variante: ['-','-','-','-','-','-','-','-','-','-'],
			}
		],

		orientation: 'black'
	}
]